import 'package:flutter/material.dart';
import 'dart:math';

class Constants {
  static List<String> jamaatList = [
    'Tablighi Jamath',
    'Jamiyath-e-Ulmaye Hind',
    'Rabtay-e-Milath',
    'Dawoodo Allah ki Taraf',
    'MRF',
    'SIO',
    'Jamiyath Ahl-e-Hadees',
    'Safa Baitul Mall',
    'Jamiyath Ahl-e-Sunathul Jamath',
    'Rifah Chaimber of Commerce',
    'Al-Falah Trust',
    'Samjhota Committee',
    'SYM',
    'Shoeba-e-Islahe Mashera Jamate Islami Hind',
    'Helping Hand Society',
    'Moment of Justice',
    'youth of Bidar',
    'Bidar Betterment Foundation',
    "Other",
    'Shaheen Staff',
    'Shaheen Alumni',
    'BBF Staff',
    'Not Assosciated with any Jamaat',
    'Education Dept',
    'Shaheen Staff (Female)',
    'Madarsa Plus',
    'IMAM MASJID',
    'Trustee',
    'GIO',
    'shoeba-e-Khawateen jamat-e-islami hind',
    'AITA',
    'majlis-ul-maulimath tehreek-e-islami hind',
    'Shoeba-e-khawateen jamat-e-ahle hadees',
    'Sunni ( ladies )',
    'Tabligi ( ladies )',
  ];

  static const List<String> quotes = [
    "Quran 2:153: 'Indeed, Allah is with the patient.'",
    "Prophet Muhammad (PBUH): 'Patience is light.' (Sahih Muslim)",
    "Quran 39:10: 'Indeed, the patient will be given their reward without account.'",
    "Quran 16:127: 'And be patient, [O Muhammad], and your patience is not but through Allah.'",
    "Prophet Muhammad (PBUH): 'The real patience is at the first stroke of a calamity.' (Sahih Bukhari)",
    "Quran 70:5: 'So be patient with gracious patience.'",
    "Prophet Muhammad (PBUH): 'When Allah loves a servant, He tests him.' (Tirmidhi)",
    "Quran 11:11: 'Except for those who are patient and do righteous deeds.'",
    "Prophet Muhammad (PBUH): 'Whoever remains patient, Allah will make him patient.' (Sahih Bukhari)",
    "Quran 3:200: 'Persevere and endure and remain stationed and fear Allah that you may be successful.'",
    "Prophet Muhammad (PBUH): 'No one has been given a gift better and more comprehensive than patience.' (Sahih Bukhari)",
    "Quran 103:2-3: 'Indeed, mankind is in loss, Except for those who have believed and done righteous deeds and advised each other to truth and advised each other to patience.'",
    "Prophet Muhammad (PBUH): 'There is no Muslim who is afflicted with a calamity and says what Allah has enjoined, ‘To Allah we belong and to Him we will return; O Allah, reward me for my affliction and compensate me with something better,’ but Allah will compensate him with something better.' (Sahih Muslim)",
    "Quran 39:10: 'Say, O My servants who have believed, fear your Lord. For those who do good in this world is good, and the earth of Allah is spacious. Indeed, the patient will be given their reward without account.'",
    "Prophet Muhammad (PBUH): 'The strong man is not the one who is good at wrestling, but the strong man is the one who controls himself in a fit of rage.' (Sahih Bukhari)",
    "Prophet Muhammad (PBUH): 'How wonderful is the affair of the believer, for his affairs are all good, and this applies to no one but the believer. If something good happens to him, he is thankful for it and that is good for him. If something bad happens to him, he bears it with patience and that is good for him.' (Sahih Muslim)",
    "Quran 16:126: 'And if you punish [an enemy, O believers], punish with an equivalent of that with which you were harmed. But if you are patient - it is better for those who are patient.'",
    "Prophet Muhammad (PBUH): 'No fatigue, nor disease, nor sorrow, nor sadness, nor hurt, nor distress befalls a Muslim, even if it were the prick he receives from a thorn, but that Allah expiates some of his sins for that.' (Sahih Bukhari)",
    "Quran 2:45: 'And seek help through patience and prayer, and indeed, it is difficult except for the humbly submissive [to Allah].'",
    "Quran 64:11: 'No disaster strikes except by permission of Allah. And whoever believes in Allah - He will guide his heart. And Allah is Knowing of all things.'"
  ];

  static List<String> schools = [
    "Nida Public School Haq Colony Bidar",
    "Branch Moon Public School Chidri Bidar",
    "Air Force School (Eng) Chidri",
    "Elite Public Bidar",
    "Saptagiri Hs Eng Kptcl Bidar",
    "Rahmani Public School Bilal Colony Bidar",
    "Little Flower High School Badroddin Colony Bidar",
    "Sanmarg Public School Badroddin Colony Bdr",
    "Pragati P.U College Bidar",
    "Kendriya Vidyalaya Afs Bidar (Code-1061)",
    "Jauhar Glorious Primary (Urdu) Sch",
    "Jasmine Higher Primary School English Medium, Bidar",
    "Shaheen Urdu High School Chidri, Bidar",
    "Syed Omer Hashmi Memorial Urdu H.S Bidar",
    "Noor Urdu Hps Pakalwada Bidar",
    "Shadan Hps School Vidya Nagar",
    "Govt Lps (Urdu) Bilal Colony Bidar",
    "Govt (Urdu) Hrps Faizpura",
    "Dorland Public School Vidya Ngr",
    "Faiz Urdu Hps Bidar",
    "Madeena Urdu Public School Mailoor",
    "Jasmeen P.U College Bidar",
    "Gulshan Education Society P.U C Bidar",
    "Bacchu Baba Hps Gandhi Nagar Bidar",
    "Al Ameen Urdu Hps (Lalwadi) Mailoor Bidar",
    "Govt Lps Bidri Colony Bidar",
    "Shaheen English Primary School Chidri Bidar",
    "Madarasa Falah E Darain Maboob Nagar Mailoor",
    "Govt Lps (Urdu) Halladakeri",
    "Gulshan Urdu H.S Faizpura Bidar",
    "The Almighty Public School",
    "Govt Lps Gandhi Nagar Bidar",
    "Disney Public School Faizapura Bidar",
    "Darul Uloom Ghps Urdu Maqdoompura",
    "Gulshan Urdu H.S Faizpura Bidar",
    "Govt Hps Mailoor Urdu Bidar",
    "Disney High School Faizpura Bidar",
    "Al-Faizan Arabic School",
    "Al Hashmiya Arabic School Mailoor",
    "Al-Badar Arabic School Maqhdoompura",
    "Nehemiah Memorial High School Bidar",
    "Dattagrir Maharaj P.U College Bidar",
    "Dattagrir Maharaj Eng School Bidar",
    "Kanyaka Parameshwari Eng. Hps",
    "St.Joseph English Medium Bdr",
    "Gnyana Sudha Vidyalaya Haladker Gumpa Ring Road Bidar",
    "Karnataka Public School Bidar",
    "Soniya Gandhi English Medium Lps School",
    "S.D.A Primary School",
    "S.D.A Eng High School Bdr",
    "Noor International Public School Noor Colony Near Horticulture Haldkeri Bidar",
    "Joy Public School H.S. Teachers Colony",
    "National English Medium Lps School B V B Compound Bidar",
    "Siddharoodh Public School",
    "Sai Spoorti Pu College Manhalli Raod Bidar",
    "Spring Fields P.S.Mailoore Bdr",
    "Naveen Public School Rampure Clny",
    "Allam Prabhu Lps Shivai Nagar Bidar",
    "Adarsh Sainik School",
    "Karnataka P.U College Bidar",
    "Sri Datta Maharaj English Lps School Chitta Raod Bidar",
    "Guru Nanak Public School Teacher Colony Manalli Raod Bdr",
    "B.V.B P.U College Bidar",
    "K.L.E. P.U. College, Ganesh Nagar Bidar",
    "Vande Mataram International School Gandhi Nagar Bidar",
    "V.K International English Medium High School Vidya Nagar",
    "Patanjali Public School K.E.B Colony Mailoor",
    "V.K. International Hps Vidya Nagar",
    "Babu Biradar P.U College Bidar",
    "Jaya Public School Bidar Near Bombay Building Vidyanagar Colony Mailoru Road Bidar",
    "Kote P.U College Biadr",
    "Holy Shepherd Hps School Bidar",
    "New Apostolic Hps English Medium",
    "Moulana Azad P U College Choubara Bidar",
    "Alma Iqbal P U College Shahi Nagar Shapur Gate Bidar",
    "N.F.P.U College Bidar",
    "Al-Ameen (Urdu) Girls High School Bidar",
    "Al-Ameen (Urdu) Hrps Shamsia Rawahal Galli Bidar",
    "Zahera (Urdu) Public School Golekhan Bidar",
    "Shaheen (Urdu) High School Ahmed Bagh Bidar",
    "Govt Girls (Urdu) Hrps Maniyartaleem Bidar",
    "Govt Urdu Hrps Gole Khana",
    "Orchid School Dargapura Bidar",
    "Orchid High School (Eng) Darga Road Bidar",
    "Shaheen (Urdu) Hrps Ahmed Bagh Bidar",
    "Zahera (Urdu) High School Girls Golekhan Bidar",
    "Radiance Public School Bidar",
    "Al - Ameen (Urdu) Boys High School Bidar",
    "Ntc Al Mahboob Urdu And Kannada High School Bidar",
    "Gawan Urdu Hrps Bidar",
    "Al Ameen Urdu Hps Sardarpura",
    "Red Rose (Eng) High School Bidar",
    "Shaheen Eng High School, Bidar",
    "Govt (Urdu) Hrps Ranreg Galli Bidar",
    "Al-Mazhar Glorious Urdu Hrps",
    "Minoritie Model Residental School (Minoritie) Maniyar Taleem Bidar",
    "Al-Ameen P.U College Bidar",
    "Shaheen Urdu Ps Ahmed Bagh Bidar",
    "Ideal Public School Rawahal Galli Bidar",
    "H.M.S.M Urdu High School Bidar",
    "Imperial Public School Bidar",
    "Al-Huda (Urdu) Hrps Bidar",
    "Moulana Azad Model School (Minoritie) Maniyar Taleem Bidar",
    "Govt Boys (Urdu)Hrps Maniyartaleem Bidar",
    "Millath (Urdu) Hrps Maniyartaleem Bidar",
    "Al-Ameen.K Rahman Khan Hrps Bidar",
    "Red Rose Public School Bidar",
    "Sai Gnyan Ind. P.U College Bidar",
    "Vishwa Gurukul Primary Scholl Naubad Bidar",
    "Disney Land Public School Pratap Nagar",
    "Sai Gyna H.S Old Rto Office Bidar",
    "Sri Rajeev Gandhi P.U College Naubad",
    "Anurag Sawant Hps New Khb Colony",
    "Maate Manikeshwari P.U College Biadr",
    "The Honey Bees Public School Bidar",
    "Shahu Maharaj P.U. College Naubad Bidar",
    "Jnanasudha P.U College Bidar",
    "Rajarshi Shahu Res H.S Bdr",
    "Sacred Heart Church Primary School",
    "Future Kids Public School Shiva Nagar Bidar",
    "Rajarshi Shahu Hps Naubad",
    "Pannalal Heeralal Lps School Bidar",
    "Excelent P U Science College Bidar",
    "Ss Sainath P U Commerce College Bidar",
    "Cambridge P.U College Bidar",
    "Cambridge Hs Eng Hyd Road Bidar",
    "Little Angels Hs En Matankeri",
    "Govt Hps & Rmsa (Urdu) Chidri",
    "Read Model (Urdu) School Maqdoomji Colony Bidar",
    "Paradise Public School Noor Khan T",
    "Moulana Azad Model School (Minoritie) Ratkalpur",
    "Madarasa Siddiqiya Hazif Ul Quran Siddiq Shah Taleem Bidar",
    "Karnataka Public Schools Govt Hps Rao Taleem Bidar",
    "Govt Hps Crs Urdu",
    "Govt Hrps Noorkhan Taleem",
    "Govt Girls Hps Ratkalpur",
    "Al Hasnath Urdu Public School Bidar",
    "Divine Ind Pu College Bidar",
    "Good Luck Public School Bidar",
    "Rauza Mission Public School Alibhag",
    "Global Public School",
    "Moulana Azad Model English School Mustaidpura (Minority)",
    "Wisdom Primary And High School",
    "Meridian H.S Jama Masjid Chw Bidar",
    "Bahamani Hps Bidar",
    "Divine Ma Urdu Prmry Schl Bdr",
    "Salf Banu Urdu Hps Bidar",
    "International Madina Model Urdu Pry. School",
    "Twinkle Public School Bidar",
    "Asra Public School",
    "Al-Hameed Hps Bidar",
    "Govt Mps Mustaidpura Bidar",
    "Al Hameed Urdu Med High School Bdr",
    "Holyfaith Pu Collage Bidar",
    "Al Maroof Glorious Urdu Hps ,Noor K",
    "Al-Maqdoom Urdu Hps And Hs",
    "Raza Public School Rao Taleem",
    "Holy Faith Public School Bdr",
    "Raina Royal Public School Panshal Taleem",
    "Lily Rose Public School Bidar",
    "Wisdom P.U College Bidar",
    "Dazzling Public School Bidar",
    "Embassy Public Schools Bidar",
    "Assooffah Arabic School Latifapura",
    "Al Badar Arabic School Chidri",
    "Al-Badar Arabic School Chidri Road",
    "Deeni Darasgah Rahmutul-Lil-Alameen Arabic School",
    "National Comp P.U College Bidar",
    "Daffodil Public School (Urdu) Shahgunj",
    "Sardar Joga Singh H.S Gurunanak Colony",
    "National High School Bidar",
    "Gurunanak P.U College Bidar",
    "Danish Urdu Public School Multani Colony Bidar",
    "Sarashwathi P.U College Bidar",
    "Shaheen Ind P.U. College Golekhana Bidar",
    "Jauhar Public School Bidar",
    "Akka Mahadevi P.U College Bidar",
    "Gulshan-E-Atfal Urdu Hps Bidar",
    "Hazrath Peerfani Hps Bidar",
    "Guru Nanak High School Bidar",
    "Guru Nanak Public School, Bidar",
    "Maharishi English Hps Bdr",
    "Maharishi Eng Medium High School Bidar",
    "Glps Shahgunj (Urdu) Bidar",
    "Jauhar P U College Shahgunj Bidar",
    "National School Bidar",
    "Govt Lps Multani Colony",
    "Govt Minority Moraji Desai Girls Residential P.U College Biadr",
    "Guru Nanak Dev Public School Bidar",
    "Noman Public School Multani Colony",
    "Good Will Public School, Bidar",
    "Govt Hps Urdu Nawbad",
    "Al-Almas Urdu Hps School Janta Colony Bidar",
    "Oasis Public School Multani Colony"
  ];

  static const primaryColor = Color(0xff002147);
  static const secondaryColor = Color(0xFF2A2D3E);
  static const bgColor = Color(0xFF212332);
  static const defaultPadding = 16.0;

  static String getRandomQuote() {
    final random = Random();
    int index = random.nextInt(quotes.length);
    return quotes[index];
  }
}
