// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpE3xPoCPIght9y_rbRgSNJWqlzokfn8Y',
    appId: '1:154097110008:web:901eb172c624b8b637240d',
    messagingSenderId: '154097110008',
    projectId: 'shaheen-namaz',
    authDomain: 'shaheen-namaz.firebaseapp.com',
    storageBucket: 'shaheen-namaz.appspot.com',
    measurementId: 'G-1YBKEF2ENQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOWRJE_hFUQaldZ32zwwbIb8uywqSktkM',
    appId: '1:154097110008:android:19178f10a415db9237240d',
    messagingSenderId: '154097110008',
    projectId: 'shaheen-namaz',
    storageBucket: 'shaheen-namaz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA701Bcgw70LHnREU3o44TOBLHRG4br6rs',
    appId: '1:154097110008:ios:1884e939fb06d2ca37240d',
    messagingSenderId: '154097110008',
    projectId: 'shaheen-namaz',
    storageBucket: 'shaheen-namaz.appspot.com',
    iosBundleId: 'com.shaheen.shaheenNamaz',
  );
}
